GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSW5kcmlzaCIsImlhdCI6MTcwNzczMTM2MSwiZXhwIjoxNzA3NzM4NTYxfQ.Gs5gOkNeQwkVS_smEI5R9v1SMfHrERVjUfREPhFbrBg

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiIsImlhdCI6MTcwNzcyOTkzN30.xBiDN0rTaZpnm5zUqlkD0F-iL31sHGBa2Oe-_aTNFXI"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Indrish"
}